### ISSUE TITLE
How was `inflamationresponse.txt` generated?

### ISSUE THREAD

**Issue by cthoyt** [huihui1126/drugSim-pathway#13]
Like #12, there is no information on how https://github.com/huihui1126/drugSim-pathway/blob/main/inflamationresponse.txt was generated nor if it were downloaded from an external source. Please either include the code that generated it or a link to the source from which it was downloaded.

If you add more code to the repository, keep in mind that it should also have information about what the requirements are to run it and all files it needs should either be referenced or automatically downloaded (it would be unproductive to go through a second round of review just for code)

**Comment by huihui1126** [comment]
Thanks for your comments. The new version of code has been uploaded in V1.1 file.
The inflamationresponse.txt is a sub file only including inflammation related GOBP terms extracting from the GOA file.
In the new version, inflamationresponse.txt was not required for extracRelation.pl, because GOA file is provided.

**Comment by huihui1126** [comment]
The inflamationresponse.txt is a sub file only including inflammation related GOBP terms extracting from the GOA file.

In the new version, inflamationresponse.txt was not required for extracRelation.pl, because GOA file is provided.
